# Generated by Django 5.1.1 on 2024-09-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_alter_category_options_contact_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Category',
            new_name='category',
        ),
    ]
